global:
  # 是否启用mcMMO检测
  check-mcmmo: false  # 默认禁用

  # 消息模板
  message:
    title: "开启全局概率翻倍 x%amount%"
    sub-title: "您当前概率翻倍倍数：%now% (权限基础倍数: %basic% 全局倍数: %total%)"

logs:
  # 日志保留天数 (0表示永久保留)
  retention-days: 30

  # 日志文件格式 (使用Java SimpleDateFormat格式)
  file-format: "yyyy-MM-dd"

  # 获取途径显示名称
  sources:
    挖矿: "挖矿"
    钓鱼: "钓鱼"
    食用: "食用"
    附魔: "附魔"

# 自定义挖矿掉落配置
dig:
  # 钻石镐配置（示例）
  "DIAMOND_PICKAXE":
    # 使用正则表达式匹配工具类型
    pattern: ".{0,}PICKAXE.{0,}"  # 匹配所有类型的镐子

    # Y坐标限制（高度限制）
    y:
      world: 128  # 主世界最高Y=50
      world_nether: 256  # 地狱无限制

    # 方块类型配置
    dig-type:
      # 石头类型
      "STONE":
        "力量宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e力量宝石§7]§a!'
        "真·力量宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 真·力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e真·力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e真·力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e真·力量宝石§7]§a!'
        "神·力量宝石":
          chance: 0.01
          string-action:
            - '[CMD]mgem give %player% 神·力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e神·力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e神·力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e神·力量宝石§7]§a!'
      "COAL_ORE":
        "保护宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 保护宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§3保护宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§3保护宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§3保护宝石§7]§a!'
        "真·保护宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 真·保护宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§3真·保护宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§3真·保护宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§3真·保护宝石§7]§a!'
      "DEEPSLATE_COAL_ORE":
        "保护宝石":
          chance: 0.8
          string-action:
            - '[CMD]mgem give %player% 保护宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§3保护宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§3保护宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§3保护宝石§7]§a!'
        "真·保护宝石":
          chance: 0.6
          string-action:
            - '[CMD]mgem give %player% 真·保护宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§3真·保护宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§3真·保护宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§3真·保护宝石§7]§a!'
      "REDSTONE_ORE":
        "荆棘宝石":
          chance: 0.4
          string-action:
            - '[CMD]mgem give %player% 荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2荆棘宝石§7]§a!'
        "真·荆棘宝石":
          chance: 0.3
          string-action:
            - '[CMD]mgem give %player% 真·荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2真·荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2真·荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2真·荆棘宝石§7]§a!'
        "神·荆棘宝石":
          chance: 0.2
          string-action:
            - '[CMD]mgem give %player% 神·荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2神·荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2神·荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2神·荆棘宝石§7]§a!'
      "DEEPSLATE_REDSTONE_ORE":
        "荆棘宝石":
          chance: 0.06
          string-action:
            - '[CMD]mgem give %player% 荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2荆棘宝石§7]§a!'
        "真·荆棘宝石":
          chance: 0.05
          string-action:
            - '[CMD]mgem give %player% 真·荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2真·荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2真·荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2真·荆棘宝石§7]§a!'
        "神·荆棘宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 神·荆棘宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§2神·荆棘宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§2神·荆棘宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§2神·荆棘宝石§7]§a!'
      "LAPIS_ORE":
        "生命宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c生命宝石§7]§a!'
        "真·生命宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 真·生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c真·生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c真·生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c真·生命宝石§7]§a!'
        "神·生命宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 神·生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c神·生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c神·生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c神·生命宝石§7]§a!'
      "DEEPSLATE_LAPIS_ORE":
        "生命宝石":
          chance: 0.08
          string-action:
            - '[CMD]mgem give %player% 生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c生命宝石§7]§a!'
        "真·生命宝石":
          chance: 0.06
          string-action:
            - '[CMD]mgem give %player% 真·生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c真·生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c真·生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c真·生命宝石§7]§a!'
        "神·生命宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 神·生命宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c神·生命宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c神·生命宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c神·生命宝石§7]§a!'
      "IRON_ORE":
        "锋利宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c锋利宝石§7]§a!'
        "真·锋利宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 真·锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c真·锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c真·锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c真·锋利宝石§7]§a!'
        "神·锋利宝石":
          chance: 0.01
          string-action:
            - '[CMD]mgem give %player% 神·锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c神·锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c神·锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c神·锋利宝石§7]§a!'
      "DEEPSLATE_IRON_ORE":
        "锋利宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c锋利宝石§7]§a!'
        "真·锋利宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 真·锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c真·锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c真·锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c真·锋利宝石§7]§a!'
        "神·锋利宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 神·锋利宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§c神·锋利宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§c神·锋利宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§c神·锋利宝石§7]§a!'
      "COPPER_ORE":
        "抢夺宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8抢夺宝石§7]§a!'
        "真·抢夺宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 真·抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8真·抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8真·抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8真·抢夺宝石§7]§a!'
        "神·抢夺宝石":
          chance: 0.01
          string-action:
            - '[CMD]mgem give %player% 神·抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8神·抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8神·抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8神·抢夺宝石§7]§a!'
      "DEEPSLATE_COPPER_ORE":
        "抢夺宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8抢夺宝石§7]§a!'
        "真·抢夺宝石":
          chance: 0.03
          string-action:
            - '[CMD]mgem give %player% 真·抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8真·抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8真·抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8真·抢夺宝石§7]§a!'
        "神·抢夺宝石":
          chance: 0.02
          string-action:
            - '[CMD]mgem give %player% 神·抢夺宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§8神·抢夺宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§8神·抢夺宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§8神·抢夺宝石§7]§a!'
      "GOLD_ORE":
        "耐久宝石":
          chance: 0.06
          string-action:
            - '[CMD]mgem give %player% 耐久宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b耐久宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b耐久宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b耐久宝石§7]§a!'
        "真·耐久宝石":
          chance: 0.04
          string-action:
            - '[CMD]mgem give %player% 真·耐久宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b真·耐久宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b真·耐久宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b真·耐久宝石§7]§a!'
        "无限宝石":
          chance: 0.01
          string-action:
            - '[CMD]mgem give %player% 无限宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b无限宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b无限宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b无限宝石§7]§a!'
          #深层金
      "DEEPSLATE_GOLD_ORE":
        "耐久宝石":
          chance: 0.08
          string-action:
            - '[CMD]mgem give %player% 耐久宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b耐久宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b耐久宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b耐久宝石§7]§a!'
        "真·耐久宝石":
          chance: 0.06
          string-action:
            - '[CMD]mgem give %player% 真·耐久宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b真·耐久宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b真·耐久宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b真·耐久宝石§7]§a!'
        "无限宝石":
          chance: 0.01
          string-action:
            - '[CMD]mgem give %player% 无限宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§b无限宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§b无限宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§b无限宝石§7]§a!'
        #绿宝石
      "EMERALD_ORE":
        "效率宝石":
          chance: 2
          string-action:
            - '[CMD]mgem give %player% 效率宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§a效率宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§a效率宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§a效率宝石§7]§a!'
        "真·效率宝石":
          chance: 1
          string-action:
            - '[CMD]mgem give %player% 真·效率宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§a真·效率宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§a真·效率宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§a真·效率宝石§7]§a!'
      #深层绿宝石
      "DEEPSLATE_EMERALD_ORE":
        "效率宝石":
          chance: 6
          string-action:
            - '[CMD]mgem give %player% 效率宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§a效率宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§a效率宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§a效率宝石§7]§a!'
        "真·效率宝石":
          chance: 4
          string-action:
            - '[CMD]mgem give %player% 真·效率宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§a真·效率宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§a真·效率宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§a真·效率宝石§7]§a!'
      "DIAMOND_ORE":
        "时运宝石":
          chance: 0.8
          string-action:
            - '[CMD]mgem give %player% 时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d时运宝石§7]§a!'
        "真·时运宝石":
          chance: 0.6
          string-action:
            - '[CMD]mgem give %player% 真·时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d真·时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d真·时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d真·时运宝石§7]§a!'
        "神·时运宝石":
          chance: 0.4
          string-action:
            - '[CMD]mgem give %player% 神·时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d神·时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d神·时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d神·时运宝石§7]§a!'
      "DEEPSLATE_DIAMOND_ORE":
        "时运宝石":
          chance: 0.4
          string-action:
            - '[CMD]mgem give %player% 时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d时运宝石§7]§a!'
        "真·时运宝石":
          chance: 0.3
          string-action:
            - '[CMD]mgem give %player% 真·时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d真·时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d真·时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d真·时运宝石§7]§a!'
        "神·时运宝石":
          chance: 0.2
          string-action:
            - '[CMD]mgem give %player% 神·时运宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§d神·时运宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§d神·时运宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§d神·时运宝石§7]§a!'
      "ANCIENT_DEBRIS":
        "力量宝石":
          chance: 0.3
          string-action:
            - '[CMD]mgem give %player% 力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e力量宝石§7]§a!'
        "真·力量宝石":
          chance: 0.2
          string-action:
            - '[CMD]mgem give %player% 真·力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e真·力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e真·力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e真·力量宝石§7]§a!'
        "神·力量宝石":
          chance: 0.1
          string-action:
            - '[CMD]mgem give %player% 神·力量宝石 1'
            - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在挖矿时发现了§7[§e神·力量宝石§7]§a!'
            - '[TITLE]10;70;30;§7§l[§6&l落日幸运系统§7§l];§a恭喜你在挖矿时找到了§7[§e神·力量宝石§7]§a!'
            - '§7[§6落日幸运系统§7]§a恭喜你找到了§7[§e神·力量宝石§7]§a!'

# 食物消耗掉落配置
consume:
  # 苹果配置
  "*":
    "生命精华":
      chance: 10  # 15%概率
      string-action:
        - '[CMD]give %player% minecraft:emerald 2'
        - '[BD]§a玩家 %player% 吃苹果时获得了生命精华!'
        - '[TITLE]10;70;30;§6§l生命精华;§a你从苹果中获得了生命能量!'
        - '[ACTION]§a+2 绿宝石'
fishing:
  "鹦鹉螺壳":
    chance: 2
    string-action:
      - '[CMD]give %player% nautilus_shell 1'
      - '[TITLE]10;70;30;§7§l[§6§l落日幸运系统§7§l];§a恭喜你在钓鱼时钓到了§7[§f鹦鹉螺壳§7] §ex1§a!'
      - '§7[§6落日幸运系统§7]§a恭喜钓到了§7[§f鹦鹉螺壳§7] §ex1§a!'
  "下界之星":
    chance: 1
    string-action:
      - '[CMD]give %player% nether_star 1'
      - '[TITLE]10;70;30;§7§l[§6§l落日幸运系统§7§l];§a恭喜你在钓鱼时钓到了§7[§e下界之星§7] §ex1§a!'
      - '§7[§6落日幸运系统§7]§a恭喜钓到了§7[§e下界之星§7] §ex1§a!'
  "海洋之心":
    chance: 1.6
    string-action:
      - '[CMD]give %player% heart_of_the_sea 1'
      - '[TITLE]10;70;30;§7§l[§6§l落日幸运系统§7§l];§a恭喜你在钓鱼时钓到了§7[§e海洋之心§7] §ex1§a!'
      - '§7[§6落日幸运系统§7]§a恭喜钓到了§7[§e海洋之心§7] §ex1§a!'
  "蛇胆":
    chance: 0.06
    string-action:
      - '[CMD]mgem give %player% 蛇胆 1'
      - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在钓鱼时钓到了§7[§c蛇胆§7] §ex1§a!'
      - '[TITLE]10;70;30;§7§l[§6§l落日幸运系统§7§l];§a恭喜你在钓鱼时钓到了§7[§c蛇胆§7] §ex1§a!'
      - '§7[§6落日幸运系统§7]§a恭喜钓到了§7[§c蛇胆§7] §ex1§a!'
  "龙胆":
    chance: 0.04
    string-action:
      - '[CMD]mgem give %player% 龙胆 1'
      - '[BD]§7[§6落日幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在钓鱼时钓到了§7[§6龙胆§7] §ex1§a!'
      - '[TITLE]10;70;30;§7§l[§6§l落日幸运系统§7§l];§a恭喜你在钓鱼时钓到了§7[§6龙胆§7] §ex1§a!'
      - '§7[§6落日幸运系统§7]§a恭喜钓到了§7[§6龙胆§7] §ex1§a!'
enchant:
  "幸运药水1":
    item-pattern: ".*"  # 匹配所有
    enchant-pattern: ".*"  # 匹配所有
    min-level: 1  # 最小附魔等级
    max-level: 30  # 最大附魔等级
    chance: 3  # 3%概率
    string-action:
      - '[CMD]mgem give %player% 幸运药水1 1'
      - '[BD]§7[§b无限幸运系统§7]§a恭喜玩家§7[§e%player%§7]§a在附魔时发现了永久附魔药水§7[§2幸运药水§7] §ex1§a!'
      - '[TITLE]10;70;30;§7§l[§b§l无限幸运系统§7§l];§a恭喜你在附魔时发现了永久附魔药水§7[§2幸运药水§7] §ex1§a!'
      - '§7[§b无限幸运系统§7]§a恭喜发现了永久附魔药水§7[§2幸运药水§7] §ex1§a!'